// @ts-check

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Reverse Bid Docs',
  tagline: 'High Level Documentation for Reverse Bid',
  url: 'https://your-docusaurus-site.example.com',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'kothagundlaramya',
  projectName: 'reverse-bid-docs-docusaurus',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'), // points to autogenerated sidebar
          routeBasePath: 'docs',                         // /docs is the base route
          editUrl:
            'https://github.com/kothagundlaramya/reverse-bid-docs-docusaurus/edit/main/',
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  plugins: [
    [
      require.resolve('@cmfcmf/docusaurus-search-local'),
      {
        indexDocs: true,
        indexBlog: false,
        indexPages: true,
        language: 'en',
      },
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'Reverse Bid Docs',
      logo: {
        alt: 'Reverse Bid Logo',
        src: 'img/logo.svg',
      },
      items: [
        // Link Docs to your first page so clicking Docs opens it
        { to: '/docs/High-level-overview', label: 'Docs', position: 'left' },
        {
          href: 'https://github.com/kothagundlaramya/reverse-bid-docs-docusaurus',
          label: 'GitHub',
          position: 'right',
        },
        { type: 'search', position: 'right' },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [{ label: 'High-Level Overview', to: '/docs/High-level-overview' }],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/kothagundlaramya/reverse-bid-docs-docusaurus',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Reverse Bid Docs.`,
    },
    docs: {
      sidebar: {
        hideable: true,               // sidebar can be collapsed
        autoCollapseCategories: true, // auto collapse categories
      },
    },
  },
};

module.exports = config;
